spring.application.name=tasktrackerapp

# Database Configuration - AWS RDS PostgreSQL
spring.datasource.url=jdbc:postgresql://tasktracker-db.c78u6swm411q.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# Server Configuration
server.port=8080
server.servlet.context-path=/api
server.forward-headers-strategy=framework

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.task.tracker=DEBUG

# AWS Cognito Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_MDJ3p4BL8
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_MDJ3p4BL8/.well-known/jwks.json

# AWS Cognito Details
aws.cognito.region=ap-south-1
aws.cognito.userPoolId=ap-south-1_MDJ3p4BL8
aws.cognito.clientId=${COGNITO_CLIENT_ID}
aws.cognito.clientSecret=${COGNITO_SECRET}

# AWS Credentials
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}

# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.theme=dark

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Enable the Prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=tasktrackerapp