services:
  tasktrackerapp:
    image: ${DOCKER_USERNAME}/tasktrackerapp:${IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      # These variables will be injected by GitHub Actions runner
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_SECRET=${COGNITO_SECRET}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      # 1. Enable Generic OAuth (Cognito)
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Cognito
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true

      # 2. Use Cognito credentials
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${COGNITO_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${COGNITO_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email

      # 3. Use current Tunnel URL
      # MUST update this variable if tunnel URL changes!
      - GF_SERVER_ROOT_URL=https://indicators-assuming-constraints-bar.trycloudflare.com/

      # 4. Cognito Endpoints
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://ap-south-1mdj3p4bl8.auth.ap-south-1.amazoncognito.com/oauth2/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://ap-south-1mdj3p4bl8.auth.ap-south-1.amazoncognito.com/oauth2/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://ap-south-1mdj3p4bl8.auth.ap-south-1.amazoncognito.com/oauth2/userInfo

networks:
  monitoring:

volumes:
  prometheus_data:
  grafana_data: